"""
Markdown reporting module for CodeSentinel.

Generates human-readable Markdown security scan reports according to the Phase 1 specification.

© 2025 Andrei Antonescu. All rights reserved.
Proprietary – not licensed for public redistribution.
"""

from typing import List

from sentinel.rules.base import Finding


def generate_markdown_report(findings: List[Finding]) -> str:
    """
    Generate a Markdown report from a list of findings.

    Args:
        findings: List of Finding objects to include in the report

    Returns:
        Markdown string containing the formatted report

    Example:
        >>> findings = [Finding(...), Finding(...)]
        >>> report = generate_markdown_report(findings)
        >>> print(report)
        # CodeSentinel Security Report

        ## Scan Summary
        - **Total Findings**: 2
        - **High Severity**: 1
        - **Medium Severity**: 1
        - **Low Severity**: 0

        ## Findings

        ### High Severity
        ...
    """
    # Build scan summary
    severity_counts = {"high": 0, "medium": 0, "low": 0}

    for finding in findings:
        severity_counts[finding.severity] += 1

    # Generate report sections
    report_parts = [
        "# CodeSentinel Security Scan Report\n",
        "# CodeSentinel Security Report\n",
        "## Scan Summary",
        f"- **Total Findings**: {len(findings)}",
        f"- **High Severity**: {severity_counts['high']}",
        f"- **Medium Severity**: {severity_counts['medium']}",
        f"- **Low Severity**: {severity_counts['low']}\n",
    ]

    # Add "No security issues detected" message for clean scans
    if len(findings) == 0:
        report_parts.append("**No security issues detected**\n")

    # Group findings by severity for organized reporting
    findings_by_severity = {
        "high": [],
        "medium": [],
        "low": []
    }

    for finding in findings:
        findings_by_severity[finding.severity].append(finding)

    # Generate findings sections
    for severity in ["high", "medium", "low"]:
        severity_findings = findings_by_severity[severity]
        if not severity_findings:
            continue

        report_parts.append(f"## {severity.title()} Severity Findings\n")

        for i, finding in enumerate(severity_findings, 1):
            report_parts.extend([
                f"### Finding {i}",
                f"- **Rule**: {finding.rule_id}",
                f"- **File**: `{finding.file_path}`",
                f"- **Line**: {finding.line or 'N/A'}",
                f"- **Confidence**: {finding.confidence or 'N/A'}",
            ])

            if finding.excerpt:
                report_parts.append(f"- **Code Excerpt**:")
                report_parts.append(f"  ```")
                report_parts.append(f"  {finding.excerpt.strip()}")
                report_parts.append(f"  ```")

            report_parts.append("")  # Empty line between findings

    # Add footer
    report_parts.extend([
        "---",
        "*Generated by CodeSentinel*"
    ])

    return "\n".join(report_parts)
