"""
Unit tests for Markdown reporting functionality.

Tests Markdown report generation and formatting for CodeSentinel security findings.
"""

import pytest
from unittest.mock import Mock

from sentinel.reporting.markdown import generate_markdown_report
from sentinel.rules.base import Finding
import pathlib


class TestMarkdownReport:
    """Test Markdown report generation."""

    def test_generate_markdown_report_empty_findings(self):
        """Test generating Markdown report with empty findings."""
        findings = []
        report = generate_markdown_report(findings)
        
        assert "# CodeSentinel Security Scan Report" in report
        assert "## Scan Summary" in report
        assert "**Total Findings**: 0" in report
        assert "**High Severity**: 0" in report
        assert "**Medium Severity**: 0" in report
        assert "**Low Severity**: 0" in report
        assert "*Generated by CodeSentinel*" in report

    def test_generate_markdown_report_with_findings(self):
        """Test generating Markdown report with actual findings."""
        findings = [
            Finding(
                rule_id="hardcoded-api-key",
                file_path=pathlib.Path("/test/app.py"),
                line=10,
                severity="high",
                excerpt="api_key = 'sk_test_1234567890abcdefghijklmnop'",
                confidence=0.8
            ),
            Finding(
                rule_id="hardcoded-database", 
                file_path=pathlib.Path("/test/config.py"),
                line=20,
                severity="medium",
                excerpt="db_url = 'postgresql://user:pass@localhost:5432/db'",
                confidence=0.9
            )
        ]
        
        report = generate_markdown_report(findings)
        
        # Check header and summary
        assert "# CodeSentinel Security Scan Report" in report
        assert "## Scan Summary" in report
        assert "**Total Findings**: 2" in report
        assert "**High Severity**: 1" in report
        assert "**Medium Severity**: 1" in report
        assert "**Low Severity**: 0" in report
        
        # Check high severity section
        assert "## High Severity Findings" in report
        assert "**Rule**: hardcoded-api-key" in report
        assert "**File**: `/test/app.py`" in report
        assert "**Line**: 10" in report
        assert "**Confidence**: 0.8" in report
        assert "api_key = 'sk_test_1234567890abcdefghijklmnop'" in report
        
        # Check medium severity section
        assert "## Medium Severity Findings" in report
        assert "**Rule**: hardcoded-database" in report
        assert "**File**: `/test/config.py`" in report
        assert "**Line**: 20" in report
        assert "**Confidence**: 0.9" in report
        assert "db_url = 'postgresql://user:pass@localhost:5432/db'" in report

    def test_generate_markdown_report_severity_grouping(self):
        """Test that findings are properly grouped by severity."""
        findings = [
            Finding(
                rule_id="rule-1",
                file_path=pathlib.Path("/test/file.py"),
                line=1,
                severity="high",
                excerpt="excerpt 1",
                confidence=0.9
            ),
            Finding(
                rule_id="rule-2",
                file_path=pathlib.Path("/test/file.py"),
                line=2,
                severity="high", 
                excerpt="excerpt 2",
                confidence=0.8
            ),
            Finding(
                rule_id="rule-3",
                file_path=pathlib.Path("/test/file.py"),
                line=3,
                severity="medium",
                excerpt="excerpt 3", 
                confidence=0.7
            ),
            Finding(
                rule_id="rule-4",
                file_path=pathlib.Path("/test/file.py"),
                line=4,
                severity="low",
                excerpt="excerpt 4", 
                confidence=0.5
            )
        ]
        
        report = generate_markdown_report(findings)
        
        # Check that sections appear in correct order
        high_index = report.find("## High Severity Findings")
        medium_index = report.find("## Medium Severity Findings")
        low_index = report.find("## Low Severity Findings")
        
        assert high_index < medium_index
        assert medium_index < low_index
        
        # Check that each section has the right number of findings
        high_section = report[high_index:medium_index]
        medium_section = report[medium_index:low_index]
        low_section = report[low_index:]
        
        assert high_section.count("### Finding") == 2
        assert medium_section.count("### Finding") == 1
        assert low_section.count("### Finding") == 1

    def test_generate_markdown_report_no_excerpt(self):
        """Test generating report with findings that have no excerpt."""
        findings = [
            Finding(
                rule_id="test-rule",
                file_path=pathlib.Path("/test/file.py"),
                line=None,
                severity="medium",
                excerpt=None,
                confidence=0.7
            )
        ]
        
        report = generate_markdown_report(findings)
        
        assert "**Rule**: test-rule" in report
        assert "**File**: `/test/file.py`" in report
        assert "**Line**: N/A" in report
        assert "**Confidence**: 0.7" in report
        # Should not include code excerpt section when excerpt is None

    def test_generate_markdown_report_long_excerpt_truncation(self):
        """Test that long excerpts are handled properly."""
        long_excerpt = "x" * 200  # Very long excerpt
        findings = [
            Finding(
                rule_id="test-rule",
                file_path=pathlib.Path("/test/file.py"),
                line=1,
                severity="high",
                excerpt=long_excerpt,
                confidence=0.9
            )
        ]
        
        report = generate_markdown_report(findings)
        
        # The excerpt should be included as-is (truncation happens in rule application, not reporting)
        assert long_excerpt in report
        assert "```" in report  # Code block markers should be present

    def test_generate_markdown_report_multiple_files(self):
        """Test report generation with findings from multiple files."""
        findings = [
            Finding(
                rule_id="rule-1",
                file_path=pathlib.Path("/project/app.py"),
                line=10,
                severity="high",
                excerpt="secret = 'value1'",
                confidence=0.8
            ),
            Finding(
                rule_id="rule-2",
                file_path=pathlib.Path("/project/config.js"),
                line=20,
                severity="high",
                excerpt="apiKey = 'value2'",
                confidence=0.9
            ),
            Finding(
                rule_id="rule-3",
                file_path=pathlib.Path("/project/utils.py"),
                line=30,
                severity="medium",
                excerpt="token = 'value3'",
                confidence=0.7
            )
        ]
        
        report = generate_markdown_report(findings)
        
        assert "/project/app.py" in report
        assert "/project/config.js" in report
        assert "/project/utils.py" in report
        assert "secret = 'value1'" in report
        assert "apiKey = 'value2'" in report
        assert "token = 'value3'" in report
